language: php

php:
  - 5.3
  - 5.4
  - 5.5

env:
  - DB=mysql

before_script:
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS freshphp;" -uroot; fi

script: phpunit --configuration phpunit_$DB.xml --coverage-text

#wtfamidoing-_